//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineStore.Domain.Model
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Product", Namespace="http://schemas.datacontract.org/2004/07/OnlineStore.Domain.Model")]
    public partial class Product : OnlineStore.Domain.Model.AggregateRoot
    {
        
        private string DescriptionField;
        
        private System.Guid IdField;
        
        private string ImageUrlField;
        
        private bool IsNewField;
        
        private string NameField;
        
        private decimal UnitPriceField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImageUrl
        {
            get
            {
                return this.ImageUrlField;
            }
            set
            {
                this.ImageUrlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsNew
        {
            get
            {
                return this.IsNewField;
            }
            set
            {
                this.IsNewField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal UnitPrice
        {
            get
            {
                return this.UnitPriceField;
            }
            set
            {
                this.UnitPriceField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AggregateRoot", Namespace="http://schemas.datacontract.org/2004/07/OnlineStore.Domain.Model")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OnlineStore.Domain.Model.Category))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OnlineStore.Domain.Model.Product))]
    public partial class AggregateRoot : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Category", Namespace="http://schemas.datacontract.org/2004/07/OnlineStore.Domain.Model")]
    public partial class Category : OnlineStore.Domain.Model.AggregateRoot
    {
        
        private string DescriptionField;
        
        private System.Guid IdField;
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="", ConfigurationName="IProductService")]
public interface IProductService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:IProductService/GetProducts", ReplyAction="urn:IProductService/GetProductsResponse")]
    OnlineStore.Domain.Model.Product[] GetProducts();
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:IProductService/GetProducts", ReplyAction="urn:IProductService/GetProductsResponse")]
    System.Threading.Tasks.Task<OnlineStore.Domain.Model.Product[]> GetProductsAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:IProductService/GetNewProducts", ReplyAction="urn:IProductService/GetNewProductsResponse")]
    OnlineStore.Domain.Model.Product[] GetNewProducts(int count);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:IProductService/GetNewProducts", ReplyAction="urn:IProductService/GetNewProductsResponse")]
    System.Threading.Tasks.Task<OnlineStore.Domain.Model.Product[]> GetNewProductsAsync(int count);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:IProductService/GetCategories", ReplyAction="urn:IProductService/GetCategoriesResponse")]
    OnlineStore.Domain.Model.Category[] GetCategories();
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:IProductService/GetCategories", ReplyAction="urn:IProductService/GetCategoriesResponse")]
    System.Threading.Tasks.Task<OnlineStore.Domain.Model.Category[]> GetCategoriesAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:IProductService/GetProductById", ReplyAction="urn:IProductService/GetProductByIdResponse")]
    OnlineStore.Domain.Model.Product GetProductById(System.Guid id);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:IProductService/GetProductById", ReplyAction="urn:IProductService/GetProductByIdResponse")]
    System.Threading.Tasks.Task<OnlineStore.Domain.Model.Product> GetProductByIdAsync(System.Guid id);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IProductServiceChannel : IProductService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class ProductServiceClient : System.ServiceModel.ClientBase<IProductService>, IProductService
{
    
    public ProductServiceClient()
    {
    }
    
    public ProductServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public ProductServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ProductServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ProductServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public OnlineStore.Domain.Model.Product[] GetProducts()
    {
        return base.Channel.GetProducts();
    }
    
    public System.Threading.Tasks.Task<OnlineStore.Domain.Model.Product[]> GetProductsAsync()
    {
        return base.Channel.GetProductsAsync();
    }
    
    public OnlineStore.Domain.Model.Product[] GetNewProducts(int count)
    {
        return base.Channel.GetNewProducts(count);
    }
    
    public System.Threading.Tasks.Task<OnlineStore.Domain.Model.Product[]> GetNewProductsAsync(int count)
    {
        return base.Channel.GetNewProductsAsync(count);
    }
    
    public OnlineStore.Domain.Model.Category[] GetCategories()
    {
        return base.Channel.GetCategories();
    }
    
    public System.Threading.Tasks.Task<OnlineStore.Domain.Model.Category[]> GetCategoriesAsync()
    {
        return base.Channel.GetCategoriesAsync();
    }
    
    public OnlineStore.Domain.Model.Product GetProductById(System.Guid id)
    {
        return base.Channel.GetProductById(id);
    }
    
    public System.Threading.Tasks.Task<OnlineStore.Domain.Model.Product> GetProductByIdAsync(System.Guid id)
    {
        return base.Channel.GetProductByIdAsync(id);
    }
}
